apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-08-31T13:27:33Z"
  labels:
    app: nginx
  name: nginx
  namespace: default
  resourceVersion: "29983"
  uid: 5c1a0204-8f69-42f9-9f6e-805e09ed6383
spec:
  clusterIP: 10.111.105.110
  clusterIPs:
  - 10.111.105.110
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32541
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
